# Generated by Django 4.2.7 on 2025-05-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietvshow',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Выходит'), ('finished', 'Завершен'), ('cancelled', 'Отменен')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
