# Generated by Django 4.2.7 on 2025-05-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movietvshow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewvote',
            name='vote_type',
            field=models.CharField(choices=[('like', 'Нравится'), ('dislike', 'Не нравится')], max_length=20, verbose_name='Тип голоса'),
        ),
    ]
