# Generated by Django 4.2.7 on 2025-05-28 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_alter_reviewvote_vote_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewvote',
            options={'verbose_name': 'Оценка отзыва', 'verbose_name_plural': 'Оценки отзывов'},
        ),
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Отметьте, если подборка должна быть видна всем пользователям', verbose_name='Публичная подборка'),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Отметьте, если подборка создана системой, а не пользователем', verbose_name='Системная подборка'),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='review',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='vote_type',
            field=models.CharField(choices=[('like', 'Нравится'), ('dislike', 'Не нравится')], max_length=20, verbose_name='Тип оценки'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('preferred_genres', models.ManyToManyField(blank=True, related_name='user_profiles', to='movies.genre', verbose_name='Предпочитаемые жанры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
