# Generated by Django 4.2.7 on 2025-06-16 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_alter_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время модерации отзыва', null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Администратор, который модерировал отзыв', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='approved', help_text='Статус модерации отзыва', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AddField(
            model_name='review',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Причина отклонения отзыва администратором', verbose_name='Причина отклонения'),
        ),
    ]
