# Generated by Django 4.2.7 on 2025-06-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_review_moderated_at_review_moderated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actordirector',
            name='photo_image',
            field=models.ImageField(blank=True, help_text='Загрузите фото актера/режиссера', null=True, upload_to='actors_photos/', verbose_name='Фото (файл)'),
        ),
        migrations.AddField(
            model_name='actordirector',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Загрузите файл с подробной биографией', null=True, upload_to='actors_resumes/', verbose_name='Резюме/Биография (файл)'),
        ),
        migrations.AddField(
            model_name='movietvshow',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Загрузите постер фильма/сериала', null=True, upload_to='movie_posters/', verbose_name='Постер (файл)'),
        ),
    ]
